sudo: required
dist: trusty
language: node_js

node_js:
- '6.9.1'
- 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8

cache:
  directories:
  - node_modules

env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-2-8
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  global:
    - CXX=g++-4.8
    - secure: PfHlDDw/BQEeYpbdasVjtGRWQ3N9obeqWOot/42sJpWDWG6XuxzIoZDJgc4rxmG1QKwfbgDrO4g/zXTCOsWXiWewd88Jau4ub6T0t3YmgRj+bND8iGmuRPvKsHo4VV5CFmZlzSx6i1lcArN9GcienXarZSnDLw94mpioEe92Mbl0MYLZQSFIS1q+NZ4rSa8mKjuXL1HMQ5+c0q3Lnj0hsREKwCBSLZ1PjH9R0vM+tRtfVi6eoW3NR5P3fWZQ6ajfecNGk9JmjAFrgg/ahR7Pp0azag7B/HLTY9PkRGXCWPJgWph2p/Q6HGieGlpf0yuwlB7uUtKwc+a+3p/A01+V1rCEEh3DrXBMKpO/Yd07JtmXWI1FdsE4Ce1o4wgErfcSlVqIruJIn5/wmHDoe8CK4i9ByzNSVYaZ5bN9EXMuTyGKB1zy8jL+7B7YPhz76lX6HO9RIIJK5DQRagfgQWy2tfN8sMa1WB5AWOfNBLvXQ495RjyaLzyYy3T1EOPnACpikA3CWwwAl/lLByCQxrnUDXhBfv/j/IRqcFeL339Zoh2NIXL+hO9cXOzH/pyX3ijfD9HFFgR2csluHdqPLJmsfKBS5zY4z2Fxpja4sz5H/RKwhHH4nbD5LFrgMOxhTwufc4vkZ40ZhRQlUvXP3VppfDc+ZsZZHys22iFIvJz23PE=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^1.0.0
- $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh coverage
- .travis/maybe-bump-version.sh

after_success:
- .travis/maybe-publish-coverage.sh
- .travis/maybe-publish-gh-pages.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: X8D7jZIYCazRy/Fe6zqHTGTnOHr6faQ4xsAh7iJvWQLuQ0kyvoVapdYtlfnVxkHGLFNlpgGts7xa45LFl4zbAhqv7toPx3+S2QNccjqgwye7GOJqRZON4Ta8cbLn3MIS0+8lFwYkpro6nl8SEjl74m9s9zHdN0i+hVgIS3HJCPwyCkcRZlfezK6Y6vz8+FNrZo/ok9GEeZi+PRwuM1s1PCghr89Ba9pufkr5d/dZ405xeMdCIiKayg7yD7dwRnvnRJ/fBsQBuKiooL8DaMocbMzxMQzDFoumffFzYJdN+uzRTKP3yvwmLUZgV6WxuvRuwyJp3f/Z0yogvnRvfpN3V0syzbuthgZhV/xf4GOCFx8XtFJp4WClWZwHMYUSafdBDxkQcsfqqat5CINDMj5wcnCVrum8h3qhc0wJp49L0I9ausMimSbxNhsJ/QgTaAXX77zBAPikUTjE9klyQTY1VWZihw8B6rhuNLJuU7qTA4x4KPu1Qx0EAGhik1MpOkWVneLXg6/XpUpvKjwn7ODrSal/N/dxErauH530fJVvNVsAyusamGDRhhUq2m0P5sTUgAGu16i3VlrpCuF3JYzssyz9BaGPaBZPZREXdOmcD9x7uCKlVL27Om3UgfpsiKWpaky5PbGY+s1J9oqyGYvv50UvEsgYBLy6j5/BVly74eg=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: '6.9.1'
    tags: true

notifications:
  slack:
    secure: Bp/Ho8zJtv0pnOBJ9BmQrsEa/NUHeRfRXXg5NmtO/DZV0TgKCKPREI/36qU+pFTaN7hLMQxMdt5npRPd+GDfWXq+ZY3w7Q2PNK2mpoZL0gi2wsT6cz0JBerzTZnwaQFJ+gLcT8GVlbWU8gAM/f8YWPdE3dc918QzafxZadN2w4XSRj/Vl8A/HneN+eBDJl93vOOQaPg0M61WAP1/unFY7SkxiWiIjf0AO+n+pqqWvCfw8a2Vkq6Jpf+t3kiPzPBuo7dheLua2CrzbkRdD2lH1N4SfbSxot0btvO0o1J2x1vYd4hM7JZNjG3C4K5FdufLE0vyfwkD8W8TOMTI2rciL57OpbrHkDbRZvBYfCjFPsk00hU5n6vwKzKr2mz+iu0ZzFlhpfzN9XyaXoE4sSQI4SgKgYgWlFjnJkEBOPb55UQ+JjhjB6Blb8DjeFxBVcCzccPEXeRV6K9mxmCVc35FyXse3mknJxm67Dlizlxo3ID8XCbd4enyHewL+dU8PHicMzzv7ufFaWRlDhJ/i9iDHX6hNLLauLx/qJmjWzPnROwo4+3yXKoCvX2S6T3Xrng/PlkdO1vN7EDGjFIDiZJhSvThRGRvvfNZdX9VuVKlc/p9EH+JaD76/IZLjDofatDlQoGVBUTHVrCRsnvsQnq1BSnr6VGY0u4p2+JLiFx+MiQ=
