sudo: required
dist: trusty
language: node_js

node_js:
- '6.9.1'
- 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8

cache:
  directories:
  - node_modules

env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  global:
    - CXX=g++-4.8
    - secure: QZvZfN3hKsHhp9ivUbfweIBCqz0ew5SkqGWDC6Vc14fZKAdciafAazZxs5cIALResMrAl179jNh1Cr18U5bgZU+Fag0v28BUYWgSVlab5G36Cderk6NLeD/zWkdbv/xceqPHy8MYGDqdb1Ysw9Jvi7nTetZCZjg6rNon0eERvtfNM+JBbRdD8rY3F+ZeBLtm+lVMy/uSMnXWmja+njO9nxaUAooaSd94YJrP6lBZ4nrjPl9KGQzPsGFHPB7s3UgQTz47GVG1If5OmPNRHgF3F7lrh41SEyRSNGSyYlnTIzCImRDHucvykiCLHCL20cUsVipXg4rmGc8j7VHw2VxDxJrskyQVgdxAgGAt92NjGwqVj9ZCii4HfDmtQYCJBQSO0Uua6/C3qQFMoIy4h39rLyN6IUTOVR/g0eQkf5L0eTJQ3KOviYwUcRPMmdNhiFr3mceZ19TvbCcIviGdnTxNxcgVYMA/KJkhPHcfScuRY+rUupNP56Ia4NGELO8w9S34/Q3052L85G/LsW3hqd9mP68Axhbo2YSjxq5q4cS13H51NTlsdcCVeruD4xbKoN5xemilg4ecGSnyo+EL4bYAQD9knf1b59N2gMadlfjDOZo2gt8gtaQYfXhwqzC2i6OygK7ebHflZ2li754DPy19PCQKQXqS2DUtYu5lhPIvHJY=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^1.0.0
- $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh

after_success:
- $(npm root -g)/pr-bumper/.travis/maybe-publish-coverage.sh
- .travis/maybe-publish-gh-pages.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: IFVNH6F+zxukdBVzM6Dppp4NhQrAiSyVa6pXJepgynwR0BX8Qll5I6A/xZB05d4B5kIAOQILaNXIuKBhT8urbv+VmnUinw17pyYb2WMlc1BL4LSVcap6MIE5Mztr1qDDLR5C/Tv+jhoK6vWrqWZuNa4WgEB0ld+2wsJLVA4SMoQMp0vVPYDRkWuu/EI861XAQi1MDiPAKZeBYimm8anCvElJt6TJzC1DZ4mynLgWcDmMFWrZ/cflf6zhAtW6ZOdQYcOx+mNEYsVoEgd2S0vEDJHz4ytWCHAA0ojr2RYs5WZiTf7/pX5aMfm60WeUx8Ym1d+xydZhxbHT1iv4FHuHeDBTezPbEUJtprTiuQuoxjJCyHb7BaoBh5qxYeNGyYhS97K/MiV2HlNoAWBaJ9PbeF+87+FvBwXE8sUtwZjZoBkJi8wD5hGcTFjSA2aa5lDyohraAL7StqRPU55NW3y6w/SwVWr5pMEW1FO8bqBsfkhYpkJEpEhG2je5ofgQIKhiU4ytoh0P3nK0Q2fteHGa/PmU68xduY7ZcGM1qDxT562Nf7HPoPOH6/37Goj6EQ1ktRGGMAxSrbGlamcqYPdvN7fSBl8JYC1OWwXOm6T3BdUICz/KC/k+gVCnlgN37B+/GIF0Jj2wQzbeU/tIPs4aG35Os6x5+Oqz9BmBpcPqIAU=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: '6.9.1'
    tags: true

notifications:
  slack:
    secure: Z3DugTejqrh8N+VfezqsUjGeKtyQjvkLxKjXDv1Kjkop0v5jDR1kKGjP/O7M1v7k7Cm9MgzzTvANR3FsFFGbb3GCtsUeT5anmy8A4xJSDdpO2Y4cflzclhTYgKIW5dbOnKtkNtKx9j1C1DwuCfklfbHMr69rwzpLbPnzax/mViAvDsaL9cjGTnhLrC9v25HLJvkf4HxcD/Gmf1QVZptiHzth4ewZbodanYNbTAvRraqWKHAMpXaONo+WJAQEr8bs19ksKc6hAIMddwrB1s8H8fDeaG/5z94oH6eT7lOKjMbfg0yHC1H/FlkCxGxt6QdHfS+OjEAxr/+N/rL0yBpF13SchZbNzHEHrR6PCQPw0w2r5wWAQA2pUESjGmGrz6do4/2cW6Y3AEmZsVJQq1I1H7Ly3W3pUWNSyOLiQfuLCH2Nvjs3IcSlRnoCJRKRkSgCVoa7WxC1aV3NX5IPWYWhtMTfBzwPFAjvw6AJGePcZ4A5zK43DESz/AHKMB/MDy64npMltl+MzABhq4YPRB/5SUZ1vuZ0KSSkglDTrLvPECj31jz4iRLRiViOAGHFQdz84WaZ2tOySIAZlx+5QSKXaAGJ2nB5Hm9DWt4uDLiAqOA0k1R7acRQdukePzP3ki4Ext8dsrawk1XSOhC+p5ekCh8uaWCNAcev3/j4KUa+kLE=
